### ISSUE TITLE
Bug: I can't fork this repo via the web UI

### ISSUE THREAD

**Issue by criticaltv** [goerli/tv#1]
Hello, I want to be able to fork this repo, so that I can make pull requests to it.

But the option to do this is not available via the web UI.

Do I need permission to fork it, or something?

**Comment by soc1c** [comment]
try now sorry

**Comment by criticaltv** [comment]
Closing, thank you @soc1c

**Comment by criticaltv** [comment]
Always create a `README.md` :) please!
